# Generated by Django 5.0 on 2023-12-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="House",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("flor", models.CharField(max_length=100, verbose_name="flor")),
                ("window", models.IntegerField(default=0, verbose_name="window")),
                ("door", models.IntegerField(default=0, verbose_name="door")),
                (
                    "roof",
                    models.CharField(
                        choices=[("FR", "Float"), ("BR", "broken")],
                        max_length=100,
                        verbose_name="type",
                    ),
                ),
            ],
            options={
                "verbose_name": "House",
                "verbose_name_plural": "Houses",
            },
        ),
    ]
