# Generated by Django 5.0 on 2023-12-24 23:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buildings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="house",
            name="flor",
        ),
        migrations.AddField(
            model_name="house",
            name="floor",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=100, verbose_name="floor"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="house",
            name="roof",
            field=models.CharField(
                choices=[("FR", "float"), ("BR", "broken")],
                max_length=100,
                verbose_name="type",
            ),
        ),
    ]
